apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-package1
  namespace: argocd
spec:
  goTemplate: true
  generators:
      # matrix 'parent' generator
    - matrix:
        generators:
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - in-cluster
          # git generator, 'child' #1
          - list:
            elements:
            - app: app1
              manifest: app1.yaml
              deploymentType: yaml
              chartVersion: 1.3.0
            - app: app2
              manifest: app2.yaml
              deploymentType: helm
              chartVersion: 1.3.1          
  template:
    metadata:
      name: "{{cluster.name}}-{{.app}}-{{.deploymentType}}"
      labels:
        environment: dev
        package: app-package1
    spec:
      project: workload-dev
      source:
        repoURL: https://github.com/devmsu/devops1.git
        targetRevision: main
        path: argo-tests/apps/values/dev/app-package1
        directory:
          include: "{{.manifest}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: app-package1
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Validate=true