apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index22
  namespace: app-package2
data:
  index.html: |
    <html>
      <body>
        <h1>I'm the app22</h1>
      </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app22
  namespace: app-package2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app22
  template:
    metadata:
      labels:
        app: nginx-app22
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-index22

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app22-service
  namespace: app-package2
spec:
  selector:
    app: nginx-app22
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
