apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workload-dev
  namespace: argocd
spec:
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
  roles:
  - name: devops-team
    policies:
    - p, proj:workload-dev:devops-team, applications, *, workload-dev/*, allow
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'