apiVersion: v1
kind: Namespace
metadata:
  name: myapp1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index2
  namespace: myapp1
data:
  index.html: |
    <html>
      <body>
        <h1>I'm the app2</h1>
      </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app2
  namespace: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app2
  template:
    metadata:
      labels:
        app: nginx-app2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-index2

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app2-service
  namespace: myapp1
spec:
  selector:
    app: nginx-app2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
